### PR TITLE
update fdb to 6.2

### PR DESCRIPTION
**Pull request by WolfDan**
Hello!

This is an update to the version 6.2 of fdb, this update adds the `fdb_transaction_get_approximate_size` function and renames `fdb_future_get_version` to `fdb_future_get_int64`

I'm not good with C at all, tho I try to replicate as much as the base code to do the update

### CODE REVIEW

**Comment by ananthakumaran** [comment]
> Test with seed 485574030 and concurrency 1 had 2 incorrect result(s) and 0 error(s) at API version 520
> Completed api test with random seed 485574030 and 1000 operations

seems like binding tester found some [issue](https://travis-ci.org/ananthakumaran/fdb/jobs/614847382?utm_medium=notification&utm_source=github_status)

**Comment by WolfDan** [comment]
I'm not quite sure how to run the binding_tester on Windows (or if is even possible)

Also I'm not sure why is it testing the 520 api since the new changes rename `fdb_future_get_version` to `fdb_future_get_int64`

I think it has something to do with the file `foundation.patch` since it the script uses it but I don't see anywhere else it is obtained or generated

Any idea what could be the issue?

**Comment by ananthakumaran** [comment]
I will debug the issue. Could you give me [push access to this pull request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)

**Comment by ananthakumaran** [comment]
Fixed the bindings tester https://github.com/ananthakumaran/fdb/compare/620. There is some issue with test that run on mac. Likely some issue at travis level
```
/usr/local/Homebrew/Library/Homebrew/brew.rb:10:in `<main>': Homebrew must be run under Ruby 2.6! You're running 2.3.3. (RuntimeError)
```

**Comment by WolfDan** [comment]
Hey @ananthakumaran the "Allow edits from mantainers" is already enabled 

Glad you fixed the issue, sorry I could not do it myself, since you've created another branch should I close this one?

**Comment by ananthakumaran** [comment]
Looks like I didn't use the proper format in the config file. I could push to the branch once I changed the format.

No need to close, we can keep it open. I will merge this branch in a day or two.

**Pull request merged**
